name: Build, Deploy to GH pages and analyze with Sonar
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
    
      - name: Build with Maven
        run: mvn clean verify --file org.sbouchet.emn.fil1A/pom.xml
      
      - name: Create Maven Site
        run: mvn site --file org.sbouchet.emn.fil1A/pom.xml
      
      - name: Deploy to GH Pages
        uses: crazy-max/ghaction-github-pages@v1
        if: success()
        with:
          target_branch: gh-pages
          build_dir: org.sbouchet.emn.fil1A/target/site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Analyze with Sonar
        #uses: sonarsource/sonarcloud-github-action@master
        #with:
        #  projectBaseDir: org.sbouchet.emn.fil1A
        #  fetch-depth: 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -Dsonar.organization=sbouchet-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN --file org.sbouchet.emn.fil1A/pom.xml
      
